import './globals.css'
import backgroundImage from '../public/background.png'

export const metadata = {
  title: 'Phrakture.com',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundImage: `url(${backgroundImage.src})` }}>{children}</body>
    </html>
  )
}
